apiVersion: v1
kind: Service
metadata:
  name: goserver-service
spec:
  #selector é responsável por filtrar todos os pods que irão incorporar esse serviço
  selector:
    app: goserver
  type: ClusterIP
  ports:
  - name: goserver-service
    port: 80 #porta do service
    targetPort: 8000 #porta do container
    protocol: TCP
