apiVersion: v1
kind: Service
metadata:
  name: goserver-service
spec:
  selector:
    app: goserver
  type: NodePort #gera uma porta dentro de todos os meus nodes 
  ports:
  - name: goserver-service
    port: 80
    targetPort: 8000
    protocol: TCP
    # porta que será acessada em qualquer node e redirecionada para o serviço
    nodePort: 30001 #range 30.000 ~ 32.767 
