apiVersion: v1
kind: Service
metadata:
  name: goserver-service
spec:
  selector:
    app: goserver
  type: LoadBalancer #tem a capacidade de gerar um ip além da porta de acesso nos nodes, permitindo assim, acessos externos
  ports:
  - name: goserver-service
    port: 80
    targetPort: 8000
    protocol: TCP